name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install
        run: npm install
      - name: build a
        run: npm run build
